display_name: Meow-Live
package_name: simple-live
maintainer:
  name: xiaoyaocz
  email: xiaoyaocz@52uwp.com
priority: optional
section: x11
installed_size: 24400
essential: false
icon: assets/logo.png

keywords:
  - Meow Live

generic_name: Meow-Live

categories:
  - Media

startup_notify: true
